apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: nginx-demo
            items:
              - key: "index.html"
                path: "index.html"
